server:
  port: 9999

spring:
  application:
    name: wx-excel
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testwx?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456


mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.dpb: info